"use client";

//
// ProviderPicker — step 1 of the add-datasource flow. Renders one clickable
// option per entry in the frozen `providers` registry, keyed on the
// descriptor id. Each option exposes `data-testid="provider-option-<id>"` so
// tests can locate it without hardcoding display names.
//
// IMPORTANT (spec Decision 3, extensibility requirement): this file contains
// NO `providerId === "..."` branches. It iterates the registry and renders a
// uniform option — adding a 4th descriptor must automatically produce a 4th
// option with no source edit here. The extensibility test
// `add-dialog-extensibility.test.tsx` enforces this via a regex scan.

import { providers } from "@ft5/ipc-contracts";
import type { ProviderDescriptor } from "@ft5/ipc-contracts";

import { Icon, type IconName } from "@/components/icon";
import { cn } from "@/lib/utils";

export interface ProviderPickerProps {
  onSelect: (providerId: string) => void;
}

export function ProviderPicker({ onSelect }: ProviderPickerProps) {
  const entries = Object.values(providers) as readonly ProviderDescriptor[];

  return (
    <ul
      data-testid="provider-picker"
      className="flex flex-col gap-2"
      role="list"
    >
      {entries.map((descriptor) => (
        <li key={descriptor.id}>
          <ProviderOption descriptor={descriptor} onSelect={onSelect} />
        </li>
      ))}
    </ul>
  );
}

interface ProviderOptionProps {
  descriptor: ProviderDescriptor;
  onSelect: (providerId: string) => void;
}

function ProviderOption({ descriptor, onSelect }: ProviderOptionProps) {
  const iconName = resolveIconName(descriptor.icon);
  return (
    <button
      type="button"
      data-testid={`provider-option-${descriptor.id}`}
      data-provider-id={descriptor.id}
      onClick={() => onSelect(descriptor.id)}
      className={cn(
        "flex w-full items-center gap-3 rounded-md border border-input bg-transparent px-3 py-2 text-left text-sm",
        "transition-colors hover:bg-accent hover:text-accent-foreground",
        "focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-none",
      )}
    >
      {iconName ? (
        <Icon
          name={iconName}
          aria-hidden
          className="text-muted-foreground size-4 shrink-0"
        />
      ) : null}
      <span className="flex flex-col">
        <span className="font-medium">{descriptor.displayName}</span>
        <span className="text-muted-foreground text-xs">
          {describeCapabilities(descriptor)}
        </span>
      </span>
    </button>
  );
}

function resolveIconName(icon: string): IconName | null {
  const known: IconName[] = [
    "sun",
    "moon",
    "monitor",
    "laptop",
    "cloud",
    "database",
    "hard-drive",
  ];
  return known.includes(icon as IconName) ? (icon as IconName) : null;
}

function describeCapabilities(descriptor: ProviderDescriptor): string {
  // Human-readable capability summary. We intentionally describe the
  // capabilities struct rather than branching on `providerId`, so a new
  // registry entry's summary is generated by the same code path.
  const parts: string[] = [];
  if (descriptor.capabilities.oauth) parts.push("OAuth sign-in");
  if (descriptor.capabilities.quota) parts.push("storage quota");
  if (descriptor.capabilities.directUpload) parts.push("direct upload");
  return parts.length > 0 ? parts.join(" · ") : "Custom provider";
}
